/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9d90a14848d5fd09f4fb6ffa58c7cce1)
interface __BaseEnv_Env {
	DB: D1Database;
	AUTH_MODE: "disabled";
	LOCAL_AUTH_TOKEN: "";
	LOCAL_AUTH_USER_ID: "";
	ALLOWED_ORIGINS: "https://sh.com,https://significanthobbies.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_MODE" | "LOCAL_AUTH_TOKEN" | "LOCAL_AUTH_USER_ID" | "ALLOWED_ORIGINS">> {}
}
